version: '3.8'

services:
  frontend:
    build:
      context: ./yapzone-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5002
    depends_on:
      - backend

  backend:
    build:
      context: ./yapzone-backend
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI
    env_file:
      - ./yapzone-backend/.env